"""Optional authentication: password hashing + signed session tokens.

Stdlib-only and offline — no external identity provider, no extra dependency. Passwords
are stored as salted PBKDF2-HMAC-SHA256 hashes; sessions are stateless HMAC-signed tokens
carried in an HttpOnly cookie. Nothing here is AI/ML; it's classic crypto from ``hashlib``
and ``hmac``.

**Auth is opt-in.** It is disabled by default so the CLI flow and the disposable
single-user UI keep working with zero configuration (and the existing test-suite stays
green). Enable it by setting ``PROOFCHECK_AUTH=on``. Configuration (all via environment):

  PROOFCHECK_AUTH            "on"/"off" (default off)
  PROOFCHECK_SECRET          HMAC signing key for session tokens (autogenerated if unset)
  PROOFCHECK_SESSION_HOURS   session lifetime in hours (default 12)
  PROOFCHECK_ADMIN_USER      bootstrap admin username (created on startup if no users)
  PROOFCHECK_ADMIN_PASSWORD  bootstrap admin password
  PROOFCHECK_ALLOW_REGISTER  "on" to expose POST /api/auth/register (default off)

When auth is disabled, every request is attributed to the ``ANONYMOUS`` user so run
history still works in single-user mode.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets
from datetime import datetime, timezone

from fastapi import Cookie, HTTPException

from . import store

SESSION_COOKIE = "proofcheck_session"
ANONYMOUS = "anonymous"
_PBKDF2_ITERATIONS = 240_000
_PBKDF2_ALGO = "sha256"

# Process-lifetime fallback secret, used only when PROOFCHECK_SECRET is unset. Generated
# once so tokens stay valid within a run; set PROOFCHECK_SECRET to persist across restarts.
_FALLBACK_SECRET = secrets.token_hex(32)


# ---- Configuration helpers (read fresh so tests/env changes take effect) -----
def _truthy(value: str | None) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes", "on"} if value else False


def auth_enabled() -> bool:
    return _truthy(os.environ.get("PROOFCHECK_AUTH"))


def registration_enabled() -> bool:
    return _truthy(os.environ.get("PROOFCHECK_ALLOW_REGISTER"))


def _secret() -> bytes:
    return os.environ.get("PROOFCHECK_SECRET", _FALLBACK_SECRET).encode("utf-8")


def _session_seconds() -> int:
    try:
        return max(60, min(7 * 86400, int(float(os.environ.get("PROOFCHECK_SESSION_HOURS", "12")) * 3600)))
    except (TypeError, ValueError, OverflowError):
        return 12 * 3600


def _now() -> int:
    return int(datetime.now(timezone.utc).timestamp())


# ---- Password hashing -------------------------------------------------------
def hash_password(password: str, salt: str | None = None) -> tuple[str, str]:
    """Return ``(hash_hex, salt_hex)`` for ``password`` (new random salt if none given)."""
    salt_bytes = bytes.fromhex(salt) if salt else secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac(
        _PBKDF2_ALGO, password.encode("utf-8"), salt_bytes, _PBKDF2_ITERATIONS
    )
    return digest.hex(), salt_bytes.hex()


def verify_password(password: str, salt_hex: str, expected_hash_hex: str) -> bool:
    candidate, _ = hash_password(password, salt_hex)
    return hmac.compare_digest(candidate, expected_hash_hex)


# ---- Session tokens (stateless, HMAC-signed) --------------------------------
def _b64e(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _b64d(text: str) -> bytes:
    pad = "=" * (-len(text) % 4)
    return base64.urlsafe_b64decode(text + pad)


def make_token(username: str) -> str:
    """Create a signed ``username:expiry`` session token."""
    expiry = _now() + _session_seconds()
    payload = f"{username}:{expiry}".encode("utf-8")
    body = _b64e(payload)
    sig = hmac.new(_secret(), body.encode("ascii"), hashlib.sha256).digest()
    return f"{body}.{_b64e(sig)}"


def verify_token(token: str | None) -> str | None:
    """Return the username for a valid, unexpired token, else ``None``."""
    if not token or len(token) > 4096 or "." not in token:
        return None
    body, _, sig = token.partition(".")
    try:
        expected = hmac.new(_secret(), body.encode("ascii"), hashlib.sha256).digest()
        if not hmac.compare_digest(_b64d(sig), expected):
            return None
        username, _, expiry = _b64d(body).decode("utf-8").rpartition(":")
        if not username or _now() >= int(expiry):
            return None
    except (ValueError, UnicodeError):
        return None
    return username


# ---- FastAPI dependency -----------------------------------------------------
def current_user(proofcheck_session: str | None = Cookie(default=None)) -> str:
    """Resolve the requesting user.

    Auth off -> everyone is :data:`ANONYMOUS`. Auth on -> a valid session cookie is
    required; otherwise raise 401. Used as a dependency on protected routes.
    """
    if not auth_enabled():
        return ANONYMOUS
    username = verify_token(proofcheck_session)
    if username is None or store.get_user(username) is None:
        raise HTTPException(status_code=401, detail="Authentication required.")
    return username


def authenticate(username: str, password: str) -> bool:
    """Check a username/password pair against the user store (constant-time)."""
    user = store.get_user(username)
    if user is None:
        # Hash anyway to avoid leaking which usernames exist via timing.
        hash_password(password)
        return False
    return verify_password(password, user.salt, user.password_hash)


def register_user(username: str, password: str) -> None:
    """Create a new user. Raises ``ValueError`` on duplicate or invalid input."""
    username = (username or "").strip()
    if len(username) > 128 or len(password) > 1024 or ":" in username:
        raise ValueError("Username must be at most 128 characters with no colon; password at most 1024 characters.")
    if not username or not password:
        raise ValueError("Username and password are required.")
    if len(password) < 8:
        raise ValueError("Password must be at least 8 characters.")
    hash_hex, salt_hex = hash_password(password)
    store.create_user(username, hash_hex, salt_hex, datetime.now(timezone.utc).isoformat())


def bootstrap_admin() -> None:
    """Create the env-configured admin user on startup if there are no users yet."""
    if not auth_enabled():
        return
    admin_user = os.environ.get("PROOFCHECK_ADMIN_USER")
    admin_pass = os.environ.get("PROOFCHECK_ADMIN_PASSWORD")
    if admin_user and admin_pass and store.count_users() == 0:
        try:
            register_user(admin_user, admin_pass)
        except ValueError:
            pass  # already exists / race — nothing to do
